Running Move unit tests
[ FAIL    ] 0x42::m::t0
[ FAIL    ] 0x42::m::t1
[ FAIL    ] 0x42::m::t2
[ FAIL    ] 0x42::m::t3
[ FAIL    ] 0x42::m::t4

Test failures:

Failures in 0x42::m:

┌── t0 ──────
│ Test did not abort with expected code. Expected test to abort with code 1, but instead it aborted with code 101 originating in an unknown location rooted here
└──────────────────


┌── t1 ──────
│ Failed to run a program on Solana VM.
│ 
│ Program log: 0xfb1, 0xfb1, 0xfb1, 0xfb1, 0xfb1
└──────────────────


┌── t2 ──────
│ Failed to run a program on Solana VM.
│ 
│ Program log: 0xfb1, 0xfb1, 0xfb1, 0xfb1, 0xfb1
└──────────────────


┌── t3 ──────
│ Failed to run a program on Solana VM.
│ 
│ Program log: 0xfb1, 0xfb1, 0xfb1, 0xfb1, 0xfb1
└──────────────────


┌── t4 ──────
│ Test did not error as expected
└──────────────────

Test result: FAILED. Total tests: 5; passed: 0; failed: 5
