name: unit test

on:
  workflow_call:

jobs:
  main:
    timeout-minutes: 60
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - id: acquire_solana_tools
        shell: bash
        run: |
          source ./scripts/acquire_solana_tools.sh
          echo "MOVE_DEV_PATH=$MOVE_DEV_PATH" >> $GITHUB_ENV
          echo "PLATFORM_TOOLS_PATH=$PLATFORM_TOOLS_PATH" >> $GITHUB_ENV

      - name: move-native tests
        run: cargo test --manifest-path external-crates/move/Cargo.toml --profile ci -p move-native

      - name: build move-cli
        run: cargo build --manifest-path external-crates/move/Cargo.toml --profile ci -p move-cli --bin move --features solana-backend
        env:
          LLVM_SYS_170_PREFIX: ${{ env.MOVE_DEV_PATH }}
          PLATFORM_TOOLS_ROOT: ${{ env.PLATFORM_TOOLS_PATH }}

      - name: build move-ir-compiler
        run: cargo build --manifest-path external-crates/move/Cargo.toml --profile ci -p move-ir-compiler

      - name: build move-compiler
        run: |
          cargo build --manifest-path external-crates/move/Cargo.toml --profile ci -p move-compiler

      - name: move-to-solana tests
        run: |
          cargo test --manifest-path external-crates/move/Cargo.toml --profile ci -p move-to-solana
        env:
          LLVM_SYS_170_PREFIX: ${{ env.MOVE_DEV_PATH }}
          PLATFORM_TOOLS_ROOT: ${{ env.PLATFORM_TOOLS_PATH }}

      - name: move-mv-llvm-compiler tests
        run: |
          cargo test --manifest-path external-crates/move/Cargo.toml --profile ci -p move-mv-llvm-compiler
        env:
          LLVM_SYS_170_PREFIX: ${{ env.MOVE_DEV_PATH }}
          PLATFORM_TOOLS_ROOT: ${{ env.PLATFORM_TOOLS_PATH }}
